apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: todo-application-deployment
spec:
  selector:
    matchLabels:
      app: todo-application
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: todo-application
    spec:
      containers:
        - name: todo-application
          image: ganesh21991/todo-application:1.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster

---
apiVersion: v1
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: todo-application
spec:
  selector:
    app: todo-application
  ports:
    - protocol: "TCP"
      port : 8080
      targetPort: 8080
  type: LoadBalancer

